apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  # annotations:
  #   cloud.google.com/neg: '{"ingress": false}'
spec:
  type: NodePort
  selector:
    app : {{ .Values.fullnameOverride }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort | default 80 }}
      nodePort: 30007
    - name: https
      port: 443
      targetPort: {{ .Values.containerPort | default 80 }}
      nodePort: 30008
